name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/heitech.zer0mqXt.core/heitech.zer0mqXt.core.csproj
    - name: Build
      run: dotnet build --no-restore ./src/heitech.zer0mqXt.core/heitech.zer0mqXt.core.csproj
    - name: Test
      run: dotnet test --verbosity normal ./unit-tests/heitech.zer0mqXt.core.tests/heitech.zer0mqXt.core.tests.csproj
